<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>WeatherAnalysis</AssemblyName>
    <RootNamespace>WeatherAnalysis</RootNamespace>
	<Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Include="**\*.ico" />
    <Resource Include="**\*.gif" />
    <Resource Remove="Images\Rainy.png" />
    <Resource Remove="Images\Rain_Animate.gif" />
    <Resource Remove="Images\Snowy.png" />
    <Resource Remove="Images\Snow_Animation.gif" />
    <Resource Remove="Images\Sun.png" />
    <Resource Remove="Images\Sun_Animation.gif" />
    <Resource Remove="Images\Umberlla_animate.gif" />
    <EmbeddedResource Include="Images\Rainy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Rain_Animate.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Snowy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Snow_Animation.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Sun.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Sun_Animation.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Umberlla_animate.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Reference Include="Syncfusion.Chart.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Chart.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Chart.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Chart.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Core.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Core.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Grid.Grouping.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Grid.Grouping.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Grid.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Grid.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Grouping.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Grouping.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Shared.Windows.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>