<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>PivotGridControl</AssemblyName>
    <RootNamespace>PivotGridControl</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="icons\RedLeftArrow.bmp" />
    <EmbeddedResource Include="icons\RedRightArrow.bmp" />
    <EmbeddedResource Include="icons\table_sql.png" />
    <EmbeddedResource Include="icons\table_sql_row.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Grid.Windows" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Grouping.Base" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="18.1.0.42" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.1.0.42" />
  </ItemGroup>
</Project>