<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>UnBoundColumns</AssemblyName>
    <RootNamespace>UnBoundColumns</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Shared.Base" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.DemoCommon" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.Data.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.SfDataGrid.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.GridCommon.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.SfListView.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.DataSource.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.SfInput.WinForms" Version="20.3.0.56" />
    <PackageReference Include="Syncfusion.Licensing" Version="20.3.0.56" />
  </ItemGroup>
</Project>