<Project>
  <PropertyGroup>
    <SyncfusionInstallLocation>C:\Program Files (x86)\Syncfusion\Essential Studio\Windows\17.2.0.28</SyncfusionInstallLocation>
  </PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)'=='net462' " > 
        <SyncfusionAssemblyLocation>net462</SyncfusionAssemblyLocation> 
    </PropertyGroup>	
    <PropertyGroup Condition=" '$(TargetFramework)'=='net8.0-windows' " > 
        <SyncfusionAssemblyLocation>net8.0-windows</SyncfusionAssemblyLocation> 
    </PropertyGroup> 
    <PropertyGroup Condition=" '$(TargetFramework)'=='net9.0-windows' " > 
        <SyncfusionAssemblyLocation>net9.0-windows</SyncfusionAssemblyLocation> 
    </PropertyGroup>
    <PropertyGroup Condition=" '$(TargetFramework)'=='net10.0-windows' " > 
        <SyncfusionAssemblyLocation>net10.0-windows</SyncfusionAssemblyLocation> 
    </PropertyGroup>	
	<PropertyGroup Condition=" '$(TargetFrameworkVersion)'=='v4.6.2' " > 
        <SyncfusionAssemblyLocation>net462</SyncfusionAssemblyLocation> 
    </PropertyGroup>

	<!-- Common Syncfusion assembly references -->
	
	<ItemGroup>
		<Reference Include="Syncfusion.Telemetry" >
			<HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\$(SyncfusionAssemblyLocation)\Syncfusion.Telemetry.dll</HintPath>
		</Reference>
	</ItemGroup>  
</Project>