<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>CalcDataGrid</AssemblyName>
    <RootNamespace>Grid</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Calculate.Base" Version="17.4.0.39" />
    <PackageReference Include="Syncfusion.Calculate.Windows" Version="17.4.0.39" />
    <PackageReference Include="Syncfusion.Licensing" Version="17.4.0.39" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>