<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefineConstants>NETCORE;</DefineConstants>
    <AssemblyName>ControlsGalore</AssemblyName>
    <RootNamespace>ControlsGalore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Diagram.Base" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Diagram.Windows" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="18.4.0.30" />
    <Reference Include="System">
      <Name>System</Name>
    </Reference>
    <Reference Include="System.Data">
      <Name>System.Data</Name>
    </Reference>
    <Reference Include="System.Design">
      <Name>System.Design</Name>
    </Reference>
    <Reference Include="System.Drawing">
      <Name>System.Drawing</Name>
    </Reference>
    <Reference Include="System.Runtime.Serialization.Formatters.Soap">
      <Name>System.Runtime.Serialization.Formatters.Soap</Name>
    </Reference>
    <Reference Include="System.Windows.Forms">
      <Name>System.Windows.Forms</Name>
    </Reference>
    <Reference Include="System.Xml">
      <Name>System.XML</Name>
    </Reference>
  </ItemGroup>
</Project>