<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>MultipleLegends</AssemblyName>
    <RootNamespace>MultipleLegends</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Chart.Base" Version="18.3.0.35" />
    <PackageReference Include="Syncfusion.Chart.Windows" Version="18.3.0.35" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.3.0.35" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="18.3.0.35" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.3.0.35" />
  </ItemGroup>
</Project>