<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>CustomCollections</AssemblyName>
    <RootNamespace>CustomCollections</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="CustomCollections.exe.manifest" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="CustomCollections.exe.manifest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Chart.Base" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Chart.Windows" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.1.0.52" />
  </ItemGroup>
</Project>