<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>DetailsViewExcelExporting</AssemblyName>
    <RootNamespace>DetailsViewExcelExporting</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;NETCORE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Core.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.DemoCommon" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Data.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.GridCommon.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.SfDataGrid.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.DataGridExport.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.SfInput.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.DataSource.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.SfListView.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Pdf.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Compression.Base" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.XlsIO.WinForms" Version="18.4.0.30" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.4.0.30" />
  </ItemGroup>
</Project>