<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>GettingStarted</AssemblyName>
    <RootNamespace>GettingStarted</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.2.0.44" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="18.2.0.44" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.2.0.44" />
  </ItemGroup>
</Project>