<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ForeignKeyReference</AssemblyName>
    <RootNamespace>ForeignKeyReference</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Grouping.Base" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Grouping.Windows" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="18.1.0.52" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.1.0.52" />
  </ItemGroup>
</Project>