<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefineConstants>NETCORE;</DefineConstants>
    <AssemblyName>Grouping</AssemblyName>
    <RootNamespace>Grouping</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DemoCommon">
      <Name>DemoCommon</Name>
    </Reference>
    <PackageReference Include="Syncfusion.Diagram.Base" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Diagram.Windows" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Licensing" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="17.3.0.14" />
  </ItemGroup>
</Project>