<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Audit_Showcase_sample</AssemblyName>
    <RootNamespace>Audit_Showcase_sample</RootNamespace>
    <Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Include="**\*.ico" />
    <None Remove="Data\Audit.pmml" />
    <Resource Remove="Images\thumb_no.png" />
    <Resource Remove="Images\thumb_yes.png" />
    <Resource Remove="Resource\Icon.ico" />
    <Resource Remove="Resource\Icon.png" />
    <EmbeddedResource Include="Data\Audit.pmml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\thumb_no.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\thumb_yes.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resource\Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resource\Icon.png" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.SfListView.WinForms" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Grid.Windows" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Licensing" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.PMML.WinForms" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.SpellChecker.Base" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Tools.Base" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="19.1.0.63" />
  </ItemGroup>
</Project>