<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ColumnChart2002</AssemblyName>
    <RootNamespace>ColumnChart2005</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Chart.Base" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Chart.Windows" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="17.3.0.14" />
    <PackageReference Include="Syncfusion.Licensing" Version="17.3.0.14" />
  </ItemGroup>
</Project>