<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ExpenseAnalysis</AssemblyName>
    <RootNamespace>ExpenseAnalysis</RootNamespace>
	<Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;NETCORE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;NETCORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Remove="Images\1-.png" />
    <Resource Remove="Images\chartstatistics.png" />
    <Resource Remove="Images\Chart_Clicked.png" />
    <Resource Remove="Images\Chart_Hover.png" />
    <Resource Remove="Images\Chart_Noraml.png" />
    <Resource Remove="Images\close.png" />
    <Resource Remove="Images\DataExporthover.png" />
    <Resource Remove="Images\DataExportnormal.png" />
    <Resource Remove="Images\ExcelExporthover.png" />
    <Resource Remove="Images\ExcelExportnormal.png" />
    <Resource Remove="Images\expense-values.png" />
    <Resource Remove="Images\ExpenseAnalysis.png" />
    <Resource Remove="Images\expense_slice_valuetitle_bg.png" />
    <Resource Remove="Images\Grid_Clicked.png" />
    <Resource Remove="Images\Grid_Hover.png" />
    <Resource Remove="Images\Grid_Normal.png" />
    <Resource Remove="Images\image2.PNG" />
    <Resource Remove="Images\left-image.png" />
    <Resource Remove="Images\logo.png" />
    <Resource Remove="Images\minimise.png" />
    <Resource Remove="Images\PdfExportHover.png" />
    <Resource Remove="Images\PdfExportNormal.png" />
    <Resource Remove="Images\Previous_MouseHover.png" />
    <Resource Remove="Images\Previous_Normal.png" />
    <Resource Remove="Images\statistics.PNG" />
    <Resource Remove="Images\WordExportHover.png" />
    <Resource Remove="Images\WordExportNormal.png" />
    <EmbeddedResource Include="Images\1-.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\chartstatistics.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Chart_Clicked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Chart_Hover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Chart_Noraml.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\close.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\DataExporthover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\DataExportnormal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\ExcelExporthover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\ExcelExportnormal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\expense-values.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\ExpenseAnalysis.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\expense_slice_valuetitle_bg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Grid_Clicked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Grid_Hover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Grid_Normal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\image2.PNG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\left-image.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\minimise.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\PdfExportHover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\PdfExportNormal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Previous_MouseHover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Previous_Normal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\statistics.PNG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\WordExportHover.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\WordExportNormal.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <Reference Include="Syncfusion.Chart.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Chart.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Chart.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Chart.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Compression.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Compression.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Core.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Core.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Data.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Data.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DataSource.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.DataSource.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DocIO.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.DocIO.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Grid.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Grid.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.GridCommon.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.GridCommon.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Office2016Theme.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Office2016Theme.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Pdf.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Pdf.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfDataGrid.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.SfDataGrid.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfDataGridConverter.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.SfDataGridConverter.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfInput.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.SfInput.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfListView.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.SfListView.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Shared.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Tools.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Tools.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.XlsIO.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.XlsIO.Base.dll</HintPath>
    </Reference>
  </ItemGroup>
   
</Project>