<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Customization</AssemblyName>
    <RootNamespace>Customization</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DemoCommon">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\DemoCommon.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfSmithChart.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.SfSmithChart.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Office2016Theme.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Office2016Theme.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Core.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Core.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Licensing.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>