<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Customization</AssemblyName>
    <RootNamespace>Customization</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.DemoCommon" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.SfSmithChart.WinForms" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Office2016Theme.WinForms" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Licensing" Version="20.1.0.55" />
  </ItemGroup>
</Project>