<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Customization</AssemblyName>
    <RootNamespace>Customization</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DemoCommon">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\DemoCommon.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfSmithChart.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.SfSmithChart.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Office2016Theme.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Office2016Theme.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Core.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Core.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\netcoreapp3.1\Syncfusion.Licensing.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>