<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ConditionalRowStyle</AssemblyName>
    <RootNamespace>ConditionalRowStyle</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Core.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.Data.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.SfDataGrid.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.GridCommon.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.SfInput.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.SfListView.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.DataSource.WinForms" Version="19.4.0.48" />
    <PackageReference Include="Syncfusion.Licensing" Version="19.4.0.48" />
  </ItemGroup>
</Project>