<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ColorUIDemo</AssemblyName>
    <RootNamespace>ColorUIDemo</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="App.ico" />
    <Content Include="sync_icon.ico" />
    <PackageReference Include="Syncfusion.Grid.Windows" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Tools.Base" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.SpellChecker.Base" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.4.0.39" />
  </ItemGroup>
  <PropertyGroup>
    <ApplicationIcon>sync_icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>