<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>MDIDemo</AssemblyName>
    <DefineConstants>TRACE;DEBUG;NETCORE</DefineConstants>
    <RootNamespace>MDIDemo</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.democommon" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Grid.Windows" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Tools.Base" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.SpellChecker.Base" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.HighContrastTheme.WinForms" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Office2019Theme.WinForms" Version="19.3.0.43" />
    <PackageReference Include="Syncfusion.Licensing" Version="19.3.0.43" />
  </ItemGroup>
  <ItemGroup>
    <None Update="RichTextBox-files\DockingClientPanel.rtf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="RichTextBox-files\DockingManager.rtf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>