<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ChartTemplate_2005</AssemblyName>
    <RootNamespace>ChartTemplate_2005</RootNamespace>
    <DefineConstants>TRACE;NETCORE</DefineConstants>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Chart.Base" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Chart.Windows" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="20.1.0.55" />
    <PackageReference Include="Syncfusion.Licensing" Version="20.1.0.55" />
  </ItemGroup>
</Project>