<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Word2007Demo_2005</AssemblyName>
    <RootNamespace>Word2007Demo_2005</RootNamespace>
	<Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Include="**\*.ico" />
    <Reference Include="Syncfusion.Grid.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Grid.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Tools.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Tools.Windows.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>