<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>MapPoints</AssemblyName>
    <RootNamespace>MapPoints</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\ShapeFiles\landslide.dbf">
      <Link>landslide.dbf</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\ShapeFiles\landslide.shp">
      <Link>landslide.shp</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\ShapeFiles\states.shp">
      <Link>states.shp</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.2.0.44" />
    <PackageReference Include="Syncfusion.Maps.Windows" Version="18.2.0.44" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="18.2.0.44" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.2.0.44" />
  </ItemGroup>
</Project>