<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>HeaderFooter</AssemblyName>
    <RootNamespace>HeaderFooter</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Core.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.DataSource.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.GridCommon.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.SfListView.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.4.0.39" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Icon\search_Colorful.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Icon\sficon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>