<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>HeaderFooter</AssemblyName>
    <RootNamespace>HeaderFooter</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
    <TargetFrameworkVersion>
    </TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Icon\search_Colorful.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Icon\sficon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <PackageReference Include="Syncfusion.Core.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.DataSource.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.GridCommon.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.SfListView.WinForms" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="18.4.0.39" />
    <PackageReference Include="Syncfusion.Licensing" Version="18.4.0.39" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
</Project>