<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>OutlookDemo_2010</AssemblyName>
    <RootNamespace>OutlookDemo_2010</RootNamespace>
	<Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
    <Reference Include="Syncfusion.Core.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Core.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Data.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Data.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.DataSource.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.DataSource.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Grid.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Grid.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.GridCommon.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.GridCommon.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfDataGrid.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.SfDataGrid.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfInput.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.SfInput.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SfListView.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.SfListView.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SpellChecker.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.SpellChecker.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Tools.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Tools.Windows.dll</HintPath>
    </Reference>
  </ItemGroup>
  
</Project>