<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DefineConstants>NETCORE;</DefineConstants>
    <AssemblyName>Network Diagram</AssemblyName>
    <RootNamespace>Network_Diagram</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.DemoCommon" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Diagram.Base" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Diagram.Windows" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Licensing" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="19.1.0.63" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="19.1.0.63" />
  </ItemGroup>
</Project>