<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>FilteredDataSample</AssemblyName>
    <RootNamespace>FilteredDataSample</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Chart.Base" Version="17.4.0.39" />
    <PackageReference Include="Syncfusion.Chart.Windows" Version="17.4.0.39" />
    <PackageReference Include="Syncfusion.Grouping.Base" Version="17.4.0.39" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="17.4.0.39" />
    <PackageReference Include="Syncfusion.Licensing" Version="17.4.0.39" />
  </ItemGroup>
</Project>