<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>FormulaAnalysis</AssemblyName>
    <RootNamespace>FormulaAnalysis</RootNamespace>
    <Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Update="Form1.resx">
      <DependentUpon>Form1.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="**\*.png" />
    <None Remove="CalcEngine.xml" />
    <Resource Remove="Images\Icon.png" />
    <Reference Include="Syncfusion.Calculate.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Calculate.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Core.WinForms">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Core.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Grid.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Grid.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Licensing.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Shared.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.SpellChecker.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.SpellChecker.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Tools.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net5.0\Syncfusion.Tools.Windows.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="CalcEngine.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Images\Icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
</Project>