<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>SuccinitySeries</AssemblyName>
    <RootNamespace>SuccinitySeries</RootNamespace>
    <Win32Manifest>app.manifest</Win32Manifest>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;NETCORE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>TRACE;NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Include="**\*.ico" />
    <None Remove="PDF\aspnetmvc4_Succinctly.pdf" />
    <None Remove="PDF\Fsharp_Succinctly.pdf" />
    <None Remove="PDF\GIS Succinctly.pdf" />
    <None Remove="PDF\HTTP_Succinctly.pdf" />
    <None Remove="PDF\iOS_Succinctly.pdf" />
    <None Remove="PDF\JavaScript_Succinctly.pdf" />
    <None Remove="PDF\jQuery_Succinctly.pdf" />
    <None Remove="PDF\Knockoutjs_Succinctly.pdf" />
    <None Remove="PDF\LightSwitch_Succinctly.pdf" />
    <None Remove="PDF\WindowsStoreApps_Succinctly.pdf" />
    <Resource Remove="pdf viewer.ico" />
    <EmbeddedResource Include="pdf viewer.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\aspnetmvc4_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\Fsharp_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\GIS Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\HTTP_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\iOS_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\JavaScript_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\jQuery_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\Knockoutjs_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\LightSwitch_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="PDF\WindowsStoreApps_Succinctly.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <PackageReference Include="Syncfusion.Compression.Base" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Core.WinForms" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Licensing" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Pdf.WinForms" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.PdfViewer.Windows" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Tools.Base" Version="20.2.0.43" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="20.2.0.43" />
  </ItemGroup>
</Project>